name: cache_munny
run-name: ${{ github.actor }} is makin it rain
on: [push]
jobs:
  cache-munny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt